### ISSUE TITLE
Take a video

### ISSUE THREAD

**Issue by Chorgo** [hyperoslo/Gallery#10]
It would be nice to be able to take a video as well. If okay, I would try to implement that feature.

**Comment by onmyway133** [comment]
@Chorgo Hi, `Gallery` is currently designed to pick video from device library for now. Looking forward to your work and then we can have a feature branch to test it 🤘

**Comment by Chorgo** [comment]
I just saw, my language wasn't on point. Thank you for understanding anyhow. Whenever I'm ready with it, I'll be happy to present it.

**Comment by glock45** [comment]
@onmyway133 @Chorgo I have a working version of video recording (via shutter button). Are you guys still wait for it or it's ready?

**Comment by Chorgo** [comment]
I didn't found the time to finish mine yet

**Comment by glock45** [comment]
Here is my work on the video recording: https://github.com/glock45/Gallery. I will make pr after I fix some issues.

**Comment by onmyway133** [comment]
@glock45 Nice, looking forward to your PR

**Comment by rlee1990** [comment]
@glock45 how can we use the one you edited?

**Comment by onmyway133** [comment]
We don't have plan to support video recording yet. If anyone wants to contribute, it would be more than welcome. Closing this for now
