### ISSUE TITLE
Can't load any images from GalleryBundle

### ISSUE THREAD

**Issue by B00jan** [hyperoslo/Gallery#100]
All of the images are missing. I don't know hot to fix it, if somebody has an idea i am open for sugestions.

**Comment by onmyway133** [comment]
@B00jan Hi, what version of Gallery do you use? And does it happen in our Demo project?

**Comment by B00jan** [comment]
I droped the Sources file to my project, so i guess it’s the latest version. Haven’t run your Demo.On first it crashed because of flash.on,off,auto images, and when i replaced it with some random images, it went through init but without any of the images that are supposed to be loaded with GalleryBundle class.

**Comment by onmyway133** [comment]
@B00jan If you use CocoaPods, it has hooks that embed `Gallery.bundle` for you. If you drop source files yourself, then you need to make sure the bundle is correctly added to your app, and that the code can access it

**Comment by B00jan** [comment]
ohhh...so thats the problem. Thank you!
