### ISSUE TITLE
UIImage's size is always 1000*750, anybody has the same bug?

### ISSUE THREAD

**Issue by alexyu1989** [hyperoslo/Gallery#109]
I think it's a PhotoKit bug.
If you select a local photo, and resolve it to UIImage. Size is 1000*750.
BUT, if you select a photo which need download from iCloud, the size is the original one.

**Comment by ofirkris** [comment]
@alexyu1989 Have you found a solution for this?

**Comment by JamesLIAOHJ** [comment]
The size of UIImage is right, I use Mojave and xcode 10.2.1 with swift5.0 ,   setting to version 4.2  in the Pod -> Targets -> Gallery build settings。
