### ISSUE TITLE
Changing done button title

### ISSUE THREAD

**Issue by impresyjna** [hyperoslo/Gallery#117]
Hi, 
It there a way to change done button title for GalleryController?

**Comment by Iyongjie** [comment]
The GridView.swift
at line 130。

**Comment by impresyjna** [comment]
But is there an option to do this using only framework downloaded from carthage?

**Comment by Iyongjie** [comment]
It seems that there is no public interface

**Comment by Schaefers** [comment]
you can add `"Gallery.Done" = "xxxx";` to your Localizable.strings.
