### ISSUE TITLE
Swift 4.2

### ISSUE THREAD

**Issue by gali8** [hyperoslo/Gallery#121]
Please release a Swift 4.2 compatible version.
Thanks.

**Comment by gali8** [comment]
I sent you a pull request.

Until merge, we can works with gallery on swift 4.2, selecting pods project/gallery/build settings and changing swift language version to **Swift 4.2**

**Comment by onmyway133** [comment]
@gali8 Hi, I just released https://github.com/hyperoslo/Gallery/releases/tag/2.2.0

**Comment by gali8** [comment]
Works perfectly. Thanks!

**Comment by onmyway133** [comment]
@gali8 Sorry that it takes a while

**Comment by choujar** [comment]
Hi folks and @onmyway133 

A whole bunch of simple name change errors including these ones:

`'addChild' has been renamed to 'addChildViewController(_:)'`

`'willMove(toParent:)' has been renamed to 'willMove(toParentViewController:)'`

I could change them manually, but that's a terrible idea.

Thanks!

**Comment by onmyway133** [comment]
@choujar Hi, can you check that you are using swift 4.2 ?

**Comment by choujar** [comment]
Yup, yup. Pulling from the latest master branch and using 4.2 for Gallery's pod build.
