### ISSUE TITLE
Could not build framework 

### ISSUE THREAD

**Issue by ChanchalW** [hyperoslo/Gallery#124]
I see repository and liked them so I thought to add this in the project. I am using Xcode 9.4.1 and Swift 4.
I have tried version 2.2.0 and 2.0.6 but getting these error while building. I have created a new project, installed pod and not able to build that project.  

![screen shot 2018-10-01 at 4 34 56 pm](https://user-images.githubusercontent.com/21195828/46285143-01c21e80-c598-11e8-808b-458f3c2d5ec5.png)

**Comment by SonicGerkor** [comment]
Same here, it's kinda weird just importing the pod and have so many errors...

**Comment by lukas2** [comment]
Is your project built using the right Swift version? 
I solved it by adding this to my Podfile:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
      if ['Gallery'].include? target.name
          target.build_configurations.each do |config|
              config.build_settings['SWIFT_VERSION'] = '4.2'
          end
      end
  end
end
```
