### ISSUE TITLE
Can't select an image and a video

### ISSUE THREAD

**Issue by onato** [hyperoslo/Gallery#127]
The UI allows me to select an image and a video, however only one of the `didSelect.*` callbacks is called.

I worked around this issue by manually accessing the `gallery.cart.video` and `gallery.cart.images` from the different callbacks.

**Comment by xinnai** [comment]
I have same problem, did you solve this problem?

**Comment by onato** [comment]
I've since switched to https://github.com/Yummypets/YPImagePicker. The only downside with it is that you can't select an animated gif.
