### ISSUE TITLE
unable to run project 

### ISSUE THREAD

**Issue by khush004** [hyperoslo/Gallery#136]
I have installed pods but i am getting following errors 

![screen shot 2018-12-17 at 2 34 24 pm](https://user-images.githubusercontent.com/29862624/50076893-e070e600-0208-11e9-8094-49596c16c21c.png)

and also i had download project but there also I wont be unable to run it .

I am using xcode 9.2
Swift 3

**Comment by adxworld** [comment]
The pods are crashing on XCode 10, swift 4.2

**Comment by ludovicoloreti** [comment]
up

**Comment by ludovicoloreti** [comment]
Anyone solved?
