### ISSUE TITLE
AirDropped Photos Not Showing Up In Camera Roll

### ISSUE THREAD

**Issue by JCsplash** [hyperoslo/Gallery#143]
Photos that are airdropped from mac to iPhone don't show up in the Gallery's camera roll (but are present in the phone's photo's app/camera roll). However, if you move photos to a new album they show up fine when you open Gallery and select that album.

Is there any setting to have airdropped photos show up by default in the users camera roll when they open Gallery?

**Comment by xinnai** [comment]
same problem

**Comment by HJfromNZ** [comment]
Hi, I believe this is to do with the format of the photos. After IOS 11, Apple replaced the format of photos from JPEG to HEIC, which can't be opened by default for some (haven't found a way for my Macbook on 10.12.6 at least). The photos did not appear when airdropped, but I was able to find the them by searching the extension ".HEIC". I then converted them to JPEGs using this website: https://heictojpg.com/, and this allowed me to open them like the others.

Hopefully this solves the problem!

**Comment by JCsplash** [comment]
Seems like iOS 13 fixed this issue. Can someone confirm this? @xinnai Are you still having this problem?

**Comment by 3lvis** [comment]
I would be happy if this is the case and Apple just fixed it :D

**Comment by JCsplash** [comment]
Yeah for me, the problem doesn't seem to be happening anymore but i could be wrong. @3lvis if you could test this too that'd be great.
