### ISSUE TITLE
Carthage build fails: Gallery.bundle: No such file or directory

### ISSUE THREAD

**Issue by JulianHidalgo** [hyperoslo/Gallery#15]
Hi guys!

I want to give Gallery a try but the build with Carthage fails:
error:(my project path)/Carthage/Checkouts/Gallery/Sources/Gallery.bundle: No such file or directory

** BUILD FAILED **
The following build commands failed:
	CpResource Sources/Gallery.bundle (my user path)/Library/Caches/org.carthage.CarthageKit/DerivedData/Gallery/1.0.0/Build/Products/Release-iphoneos/Gallery.framework/Gallery.bundle

(I removed my project and user path from the text above). Do you have any idea of what might be wrong? Thanks a lot :)!

**Comment by onmyway133** [comment]
@JulianHidalgo Hi, this is because this is not yet added to project. We will fix this

**Comment by JulianHidalgo** [comment]
Hi @onmyway133 ! Thanks for the quick reply, I'll wait then :).

**Comment by onmyway133** [comment]
@JulianHidalgo Hi, we've fixed it. Please check https://github.com/hyperoslo/Gallery/releases/tag/1.1.0

**Comment by JulianHidalgo** [comment]
Awesome! Checking it out right away :D.

**Comment by JulianHidalgo** [comment]
It works and looks great, thanks a lot for sharing this :)!

**Comment by JulianHidalgo** [comment]
Also really like the dynamic background with Lightbox :).

**Comment by onmyway133** [comment]
@JulianHidalgo Nice. Then I will close this 🎸
