### ISSUE TITLE
Adding Full Screen option for iOS 13

### ISSUE THREAD

**Issue by Rcicen** [hyperoslo/Gallery#163]
iOS 13 Default presentation style has changed the FullScreen presentation into a modal page sheet. Can you add an option for us to select fullScreen option :)

https://medium.com/@hacknicity/view-controller-presentation-changes-in-ios-13-ac8c901ebc4e

**Comment by 0xfeedface1993** [comment]
You can specific `modalPresentationStyle` with `.fullScreen`, but there are problem work with LightBox in `.formSheet` style (iOS 13).

```swift
let gallery = GalleryController()
gallery.modalPresentationStyle = .fullScreen
self.present(gallery, animated: true, completion: nil)
```
