### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by Rcicen** [hyperoslo/Gallery#166]
**Problem:**
When the gallery is in arabic with semanticContentAttribute set as .rightToLeft some components chance its location while others don't.

It also causes the flash button to overlap with its title

<img width="296" alt="Screen Shot 2019-10-07 at 16 57 58" src="https://user-images.githubusercontent.com/44670959/66318359-d4831b80-e923-11e9-91f2-c5da71d7ab6c.png">
<img width="317" alt="Screen Shot 2019-10-07 at 16 57 36" src="https://user-images.githubusercontent.com/44670959/66318360-d4831b80-e923-11e9-9676-c37e5e241912.png">

**Solution:**
Adding support for arabic languages which use rightToLeft display.

I would really appreciate if you can make a fix for it 🙌

**Comment by smindia1988** [comment]
**=>** To fix the issue, causes the flash button to overlap with its title, put below code into "TripleButton" class, Replace "setup()" function code with below my code:

**func setup() {**
        titleLabel?.font = Config.Font.Text.semibold.withSize(12)
        
        if(UIView.appearance().semanticContentAttribute == .forceRightToLeft) {//SMP: Fix
            //RTL
            //print("RTL")
            imageEdgeInsets = UIEdgeInsets(top: 0, left: 10, bottom: 0, right: 0)
        } else {
            //LTR
            //print("LTR")
            imageEdgeInsets = UIEdgeInsets(top: 0, left: -10, bottom: 0, right: 0)
        }
        
        setTitleColor(UIColor.gray, for: .highlighted)
        
        select(index: selectedIndex)
    }


**=>** To make the Localised text for RTL, put below text into your **Localizable.strings**

//Gallery Custom Class (English)
"Gallery.Videos.Title" = "VIDEOS";
"Gallery.Camera.Title" = "CAMERA";
"Gallery.Images.Title" = "PHOTOS";
"Gallery.Camera.Flash.Off" = "OFF";
"Gallery.Camera.Flash.On" = "ON";
"Gallery.Camera.Flash.Auto" = "AUTO";
"Gallery.Done" = "Done";
"Gallery.EmptyView.Text" = "Nothing to show";
"GalleryAndCamera.Permission.Info" = "Please grant access to photos and the camera.";
"Gallery.Permission.Info" = "Please grant access to photos.";
"Gallery.Permission.Button" = "Go to Settings";
"Gallery.AllVideos" = "ALL VIDEOS";

//Gallery Custom Class (Arabic)
"Gallery.Videos.Title" = "أشرطة فيديو";
"Gallery.Camera.Title" = "الة تصوير";
"Gallery.Images.Title" = "الصور";
"Gallery.Camera.Flash.Off" = "إيقاف";
"Gallery.Camera.Flash.On" = "على";
"Gallery.Camera.Flash.Auto" = "تلقاءي";
"Gallery.Done" = "منجز";
"Gallery.EmptyView.Text" = "لا شيء لاظهار";
"GalleryAndCamera.Permission.Info" = "يرجى منح حق الوصول إلى الصور والكاميرا.";
"Gallery.Permission.Info" = "يرجى منح حق الوصول إلى الصور.";
"Gallery.Permission.Button" = "اذهب للاعدادات";
"Gallery.AllVideos" = "جميع مقاطع الفيديو";

**Comment by smindia1988** [comment]
> **Problem:**
> When the gallery is in arabic with semanticContentAttribute set as .rightToLeft some components chance its location while others don't.
> 
> It also causes the flash button to overlap with its title
> 
> <img alt="Screen Shot 2019-10-07 at 16 57 58" width="296" src="https://user-images.githubusercontent.com/44670959/66318359-d4831b80-e923-11e9-91f2-c5da71d7ab6c.png">
> 
> <img alt="Screen Shot 2019-10-07 at 16 57 36" width="317" src="https://user-images.githubusercontent.com/44670959/66318360-d4831b80-e923-11e9-9676-c37e5e241912.png">
> 
> **Solution:**
> Adding support for arabic languages which use rightToLeft display.
> 
> I would really appreciate if you can make a fix for it 🙌

i have added the solution for RTL. Please refer.
