### ISSUE TITLE
Gallery vs. ImagePicker?

### ISSUE THREAD

**Issue by JulianHidalgo** [hyperoslo/Gallery#17]
Hi!

I'm a bit confused about the difference between Gallery and ImagePicker. I see Gallery has extra support for videos, but I also see ImagePicker has been optimized more? From ImagePicker's readme:
"ImagePicker has been optimized to give a great user experience, it passes around referenced images instead of the image itself which makes it less memory consuming. This is what makes it smooth as butter."
Is this something missing in Gallery or done in a different way? Thanks!

- Julian

**Comment by richardtop** [comment]
Hi Julian,
I'm not the contributor of this library, but from my point of view the only difference is the UI design. Each of these pickers represent own usage pattern, the `ImagePicker` is focused taking small number of images quickly while the `Gallery` is to select larger amount of photos/videos from the whole camera roll, which can be quite big.

**Comment by onmyway133** [comment]
@JulianHidalgo thanks for your question and thanks @richardtop for the correct answer. If you take a look at the source code, both are using the same refactored `CameraMan`. The different is the use case

**Comment by richardtop** [comment]
@onmyway133 why not to extract `CameraMan` to a separate dependency then?

**Comment by onmyway133** [comment]
@richardtop It is small so we didn't extract it that time. But that's thing we can consider
@JulianHidalgo I think I will close this PR for now. Thanks for asking ❤️
