### ISSUE TITLE
Repeatedly rotate the phone on camera view leads to crash.

### ISSUE THREAD

**Issue by 150vb** [hyperoslo/Gallery#175]
Use this page configuration:
Config.tabsToShow = [.imageTab, .cameraTab]

When I open the camera page with my iPhone(iPhone XR or iPhone 11 Pro) and do continuous rotate, it causes crash.
It seem that PagesController`s UIScrollViewDelegate extension case Index out of range

**Comment by 3lvis** [comment]
Hi @150vb, thanks for pointing this issue, unfortunately we don't have someone to follow up on this project at the moment if you or someone want to give it a go at fixing this issue I'm happy to assist.

**Comment by 3lvis** [comment]
Should be fixed now, let me know if it's still an issue

**Comment by 150vb** [comment]
> Should be fixed now, let me know if it's still an issue

Thank you for your response. I rename the branch and forget to push again, haha

**Comment by 3lvis** [comment]
Hahaa, thanks!
