### ISSUE TITLE
Low image quality

### ISSUE THREAD

**Issue by BaranBerk** [hyperoslo/Gallery#178]
Hi,
I have tried with camera and also by picking from my gallery. Images resolution are always very bad how can I increase image quality?

Thank you

**Comment by 3lvis** [comment]
Hi @BaranBerk, I haven't had the same issue, are we talking about iPhone or iPad? Were you able to resolve this issue?

**Comment by 3lvis** [comment]
Should be fixed now, thanks for reporting
