### ISSUE TITLE
How to restrict photo selection to 25

### ISSUE THREAD

**Issue by gowtham-iOSDev** [hyperoslo/Gallery#179]
Config.Camera.imageLimit == 25

where should i change this ? camera controller or image controller

_Originally posted by @gowtham-iOSDev in https://github.com/hyperoslo/Gallery/issues/172#issuecomment-704223367_

**Comment by 3lvis** [comment]
Hi,

Just call Config.Camera.imageLimit = 25 before you present it. :)
