### ISSUE TITLE
AVAssetExportSession Unknown error -17507 on VideoEditor

### ISSUE THREAD

**Issue by khadkasuman** [hyperoslo/Gallery#185]
While editing some videos (downloaded from whatsapp or iCloud), I am facing this strange error. Upon debugging I found out that while exporting the video with AVAssetExportSession in VideoEditor, the error appears.

``
Optional(Error Domain=AVFoundationErrorDomain Code=-11800 "The operation could not be completed" UserInfo={NSLocalizedFailureReason=An unknown error occurred (-17507), NSLocalizedDescription=The operation could not be completed, NSUnderlyingError=0x280066520 {Error Domain=NSOSStatusErrorDomain Code=-17507 "(null)"}})
``

**Comment by khadkasuman** [comment]
Fixed the issue by requesting AVAsset from PHImageManager.

``
  let options = PHVideoRequestOptions()
  options.isNetworkAccessAllowed = true
  options.deliveryMode = .highQualityFormat
  PHImageManager().requestAVAsset(forVideo: video.asset, options: options) { (asset: AVAsset?, _, _) in
      if let asset = asset {
           VideoEditor().crop(avAsset: asset) { (url) in
                print(url)  // video url
          }
       }
``

**Comment by khadkasuman** [comment]
Fixed the issue by requesting AVAsset from PHImageManager in didSelectVideo delegate.
```Swift
let options = PHVideoRequestOptions()
options.isNetworkAccessAllowed = true 
options.deliveryMode = .highQualityFormat 
PHImageManager().requestAVAsset(forVideo: video.asset, options: options) { (asset: AVAsset?, _, _) in 
	if let asset = asset { 
    	VideoEditor().crop(avAsset: asset) { (url) in 
            print(url) // video url 
         } 
     }
}
```

**Comment by 3lvis** [comment]
I'm glad you got this working, sorry for the lack of follow up
