### ISSUE TITLE
Rotation Support

### ISSUE THREAD

**Issue by douglas-srs** [hyperoslo/Gallery#21]
Can we have Rotation Support please?

**Comment by onmyway133** [comment]
@douglas-srs Hi, thanks for checking this out. Unfortunately this is designed for portrait only

**Comment by douglas-srs** [comment]
Really? I tweaked it a little to see how it would look in landscape and it looks awesome, for me anyway :P, don't worry and thanks for providing such a great image/video picker!

**Comment by onmyway133** [comment]
@douglas-srs Glad that it works for you 🎉
