### ISSUE TITLE
Turn off video selection

### ISSUE THREAD

**Issue by jpsanabria** [hyperoslo/Gallery#22]
I would like to remove the video selection tab. How can I do this within the Gallery.Config?

**Comment by onmyway133** [comment]
@jpsanabria there is this PR https://github.com/hyperoslo/Gallery/pull/20 which has `show video` flag that can toggle that, maybe you can check that branch first

**Comment by jpsanabria** [comment]
@onmyway133 it doesn't look like those changes have been approved however

**Comment by irajkumariOS** [comment]
@jpsanabria i hided the video tab for that you need to change the following code in the GalleryController.swift file.

just remove the videosController and then video tab will not be shown.

func makePagesController() -> PagesController {
    let controller = PagesController(controllers: [imagesController, cameraController])   //my code
  //  let controller = PagesController(controllers: [imagesController, cameraController, videosController])  //previous code

    controller.selectedIndex = Page.camera.rawValue

    return controller
  }

**Comment by hyouuu** [comment]
I'd suggest also add optional camera, as well as having camera being able to use the original ratio and quality rather than the whole screen ratio which comes with lower image quality

**Comment by onmyway133** [comment]
@jpsanabria @irajkumariOS @hyouuu Hi, you can check out 1.2.0 https://github.com/hyperoslo/Gallery/releases/tag/1.2.0 which has `Config.showsVideoTab`
