### ISSUE TITLE
Camera flashlight is default to off but still has flashlight

### ISSUE THREAD

**Issue by hyouuu** [hyperoslo/Gallery#23]
When I open GalleryController which opens the camera by default, it has the flashlight being "off". However, in dark environment it will still flash

**Comment by onmyway133** [comment]
@hyouuu Hi, I can't reproduce this issue. One way is to debug in function `CameraMan.flash` and see what flash mode is being used at that time?

**Comment by hyouuu** [comment]
Seems to be fixed in the latest release :)
