### ISSUE TITLE
Add default tab option, as well as having camera being able to use the original ratio and quality 

### ISSUE THREAD

**Issue by hyouuu** [hyperoslo/Gallery#25]
Firstly thanks for the library!
Please add an optional camera (similar to the optional video) so people could use this as a gallery picker if needed.
Then a default first tab option would also be great.
The current camera is using full screen ratio, which has lower image quality - maybe another option to choose which mode the camera uses.

**Comment by onmyway133** [comment]
@hyouuu Hi, sounds like good idea. How about submitting a PR? We're looking forward to see it 👍

**Comment by onmyway133** [comment]
This https://github.com/hyperoslo/Gallery/pull/28 fixed this issue
