### ISSUE TITLE
compile error on missed protocol method

### ISSUE THREAD

**Issue by tomisacat** [hyperoslo/Gallery#26]
I've implemented a subclass of `UIViewController` and make it conform to `GalleryControllerDelegate` like this:

```swift
class CaptureViewController: UIViewController, GalleryControllerDelegate {
    func galleryControllerDidCancel(_ controller: GalleryController) {
        controller.dismiss(animated: true, completion: nil)
    }
    
    func galleryController(_ controller: GalleryController, didSelectVideo video: Video) {
        controller.dismiss(animated: true, completion: nil)
    }
    
    func galleryController(_ controller: GalleryController, didSelectImages images: [UIImage]) {
        controller.dismiss(animated: true, completion: nil)
    }
    
    func galleryController(_ controller: GalleryController, requestLightbox images: [UIImage]) {
        controller.dismiss(animated: true, completion: nil)
    }
 
    // other stuff
}
```

but the compiler always shows:

>Type 'CaptureViewController' does not conform to protocol 'GalleryControllerDelegate'
>
>Protocol requires function 'galleryController(_:didSelectVideo:)' with type '(GalleryController, Video) -> ()'; do you want to add a stub?
>
>Candidate has non-matching type '(GalleryController, Video) -> ()'

I don't see any mistake I've taken(in fact, my code is just follow your demo project). So what's wrong with me?

Appreciate.

**Comment by tomisacat** [comment]
My environment is Xcode 8.3.2 with Swift 3.1

**Comment by onmyway133** [comment]
@tomisacat Hi, what version of Gallery do you have? Also, check if you have any other class named `Video` in your project?

**Comment by tomisacat** [comment]
@onmyway133 I'm using Gallery 1.2 and the problem solved. You're right, I have a struct also named `Video`, which compel me to use `Gallery.Video` instead of `Video` directly. Thank you very much!
