### ISSUE TITLE
How can I get the path to selected image?

### ISSUE THREAD

**Issue by PeCheRukiN** [hyperoslo/Gallery#30]
Hello! How can I get the path to selected image?

**Comment by onmyway133** [comment]
@PeCheRukiN Hi, as you know, we return the `UIImage` object in the delegate method `func galleryController(_ controller: GalleryController, didSelectImages images: [UIImage])`. So it is not possible for now to get the path

**Comment by PeCheRukiN** [comment]
Ok, thanks.

**Comment by NasrullahKhan** [comment]
Hi, the issues is closed already. by the way i'm sharing my efforts so it may help someone 

import Photos

and add these lines will get the the image to UIImage or images URL

    func galleryController(_ controller: GalleryController, didSelectImages images: [Image]) {
        if images.count > 0 {
            
            // get all selected images URL
            for image in images {
                if image.asset.mediaType == .image {
                    image.asset.requestContentEditingInput(with: PHContentEditingInputRequestOptions()) { (eidtingInput, info) in
                        if let input = eidtingInput, let imgURL = input.fullSizeImageURL?.absoluteString {
                         print("imgURL", imgURL)
                      }
                    }
                }
            }
            
            Image.resolve(images: images) { (resolvedImages) in
                self.selectedImages = resolvedImages as! [UIImage]
            }
        }
        controller.dismiss(animated: true, completion: nil)
    }
