### ISSUE TITLE
Loading image from iCloud

### ISSUE THREAD

**Issue by jpsanabria** [hyperoslo/Gallery#31]
If an image is not on the device and needs to be loaded from the network, how can I enable that feature?

**Comment by jpsanabria** [comment]
Any progress on this?

**Comment by davidpflugpeil** [comment]
It would be really great if there was a solution to this!

**Comment by dannyshmueli** [comment]
+1

**Comment by davidpflugpeil** [comment]
Check out this repo by @geor-kasapidi: https://github.com/geor-kasapidi/Gallery/tree/feature/icloud_images

**Comment by loasjerry** [comment]
Have to do it via async call and set the isNetworkAccessAllowed to false.

**Comment by onmyway133** [comment]
@jpsanabria @dannyshmueli @loasjerry @davidpflugpeil Hi, sorry for late response, can you check https://github.com/hyperoslo/Gallery/releases/tag/2.0.4 ?
