### ISSUE TITLE
Remove bottom bar indicating photos, camera and video

### ISSUE THREAD

**Issue by pareekkhushboo77** [hyperoslo/Gallery#34]
Hi, First of all thanks for such a beautiful and easy to integrate library,
I was looking for a way to remove bottom indicator view, 

Thanks.

**Comment by onmyway133** [comment]
@pareekkhushboo77 Hi, the bottom indicator view is managed by an internal `pagesController`, so you can't change it for now. You can fork this project and make your own changes 😎

**Comment by pareekkhushboo77** [comment]
@onmyway133 , can you please guide me that what all changes i have to make, as i am new to swift development?

**Comment by onmyway133** [comment]
@pareekkhushboo77 Hi, you can remove the `pageIndicator` https://github.com/hyperoslo/Gallery/blob/master/Sources/Utils/Pages/PagesController.swift#L79

**Comment by pareekkhushboo77** [comment]
Thanks.
