### ISSUE TITLE
Video editor not working/editedVideo equals nil

### ISSUE THREAD

**Issue by blurtime** [hyperoslo/Gallery#41]
I recently started using this library and really like the layout and that it takes care of some things like maximum length and saving photos/videos (so to say edited since only the first seconds allowed are saved) to the photos automatically. However, I now encountered a problem which I cannot solve. I initially used the following code in the `didSelectVideo` function (very similar to what is presented in the `README.md`):

    internal var gallery: GalleryController?
    internal let editor: VideoEditing = VideoEditor()

    func galleryController(_ controller: GalleryController, didSelectVideo video: Video) {    
        controller.dismiss(animated: true, completion: nil)
        
        editor.edit(video: video) { (editedVideo: Video?, tempPath: URL?) in
            DispatchQueue.main.async {
                if let tempPath = tempPath {
                    let controller = AVPlayerViewController()
                    controller.player = AVPlayer(url: tempPath)
                    
                    self.present(controller, animated: true, completion: nil) 
                }
            }
        }
    }

The `video` in the parantheses of `edit` seems to have the right properties when I set a breakpoint somewhere (i.e. right amount of seconds the selected video lasts). Moreover, the values match those which can be found under `self > gallery > cart > videos`. But if I now enter the `edit` function and the breakpoint at `DispatchQueue.main.async` is hit, it tells me `editedVideo` equals `nil`. In addition to that, `tempPath` appears to be `some`(?) and only becomes a path when `AVPlayer(url: tempPath)` is hit although this doesn't seem to be a problem. The problem is no viewcontroller is presented. If I add a simple print in the completion handler of the `present` function, nothing is ever printed.

Since `video` wasn't `nil` I tried the following code (in `didSelectVideo) - which didn't work either:

        print(video) //prints "Gallery.Video"

        controller.dismiss(animated: true, completion: nil)
        
        video.fetchPlayerItem { (playerItem) in
            DispatchQueue.main.async {
                let avPlayer = AVPlayer(playerItem: playerItem)
                
                let avPlayerViewController = AVPlayerViewController()
                avPlayerViewController.player = avPlayer
                
                //nothing happens
                self.present(avPlayerViewController, animated: true, completion: {
                    print(1)
                })
            }
        }

On top of all this, there appears to be a memory leak I couldn't find a soltuion for either. Can someone help me and explain why this is happening? I would really appreciate your help!

**Comment by blurtime** [comment]
Still don't know how to display my video after selecting one. Posted a [question on stackoverflow](https://stackoverflow.com/questions/45822332/transfer-mp4-from-temporary-path-to-documents-directory-and-play) now.

**Comment by onmyway133** [comment]
@blurtime Hi,

1. Is this an error that prevents the app from compiling? It shows warnings only for me
> In addition to that I have another question: Why do both returns inside the if statements of the code below cause this error:

2. So the video is selected successfully, but `fetchPlayerItem` or `video editing` does not work for it. The purpose of video editing is to resize and crop video, you can ignore if you don't need it. Did you try on the sample project to see if it works or not?
> Since video wasn't nil I tried the following code

**Comment by blurtime** [comment]
@onmyway133 Hello, first of all thank you for replying! 

1. I am sorry for my inaccuracy... They aren't errors as in errors which prevent the app from compiling...  They're only warnings, but isn't they're a better way than leaving the warnings there? 

2. As the sample project did not work in my app, either, I created a new project and the editor as well as `fetchPlayerItem` worked fine which made me wonder why... 
After experimenting a little I found that the reason why it didn't seem to work was because I used the `ViewController() //the sample project` in a `UITabBarController` although I can absolutely not explain how this causes the controller not to be presented: I.e. when I change `window?.rootViewController = BarController() //my UITabBarController containing ViewController() in one of its tabs` to `window?.rootViewController = ViewController() //just the sample project` in my AppDelegate it suddenly works. Any idea as to what could cause this and how one could solve it?

Side note: Just in case you should be wondering why I am doing this using `window?.rootViewController`, I prefer not using storyboards...

**Comment by onmyway133** [comment]
@blurtime Hi,

1. It's a bit annoying, we need to fix that somehow
2. `Gallery` is just a  view controller that you present, so it has nothing with the way the project is setup or how it is displayed. Could you send me the minimal project that reproduces the issue?

**Comment by blurtime** [comment]
@onmyway133 Hi, 

1. sounds great!
2. Sure, I just created another project pretty much reproducing the error. Something interesting is that I all of the sudden get the warning below. Note that this error occurs when I try to present the view controller:

       Warning: Attempt to present <AVPlayerViewController: 0x1010a3200> on <GalleryTab.ViewController: 0x100e0c6c0> whose view is not in the window hierarchy!

However, this is actually not what I want, I was rather thinking about something like this: 
        
    video.fetchPlayerItem { (playerItem) in
        DispatchQueue.main.async {
            let player = AVPlayer(playerItem: playerItem)
            let playerLayer = AVPlayerLayer(player: player)
              
            playerLayer.frame = self.view.frame
            self.view.layer.addSublayer(playerLayer)

            player.play()
        }
    }

The same applies to it, i.e. if it's used immediately (`window?.rootViewController = ViewController() //sample project with modification presented above`), it works, if I put it in the `BarController()` again as shown below (and of course do this: `window?.rootViewController = BarController()`), nothing happens _and_ there's no error.

My code: 

    import UIKit

    class BarController: UITabBarController, UITabBarControllerDelegate {
        
        override func viewDidLoad() {
            super.viewDidLoad()
            
            self.delegate = self
        }
        
        override func viewWillAppear(_ animated: Bool) {
            super.viewWillAppear(animated)
            
            let tabOne = ViewControllerOne() //some ViewController doing nothing 
            let tabOneBarItem = UITabBarItem(title: "Home", image: #imageLiteral(resourceName: "home"), selectedImage: #imageLiteral(resourceName: "home"))
            
            tabOne.tabBarItem = tabOneBarItem
            
            let tabTwo = ViewController() //sample project or sample project with modification presented above
            let tabTwoBarItem = UITabBarItem(title: "Create", image: #imageLiteral(resourceName: "home"), selectedImage: #imageLiteral(resourceName: "home")) /
            
            tabTwo.tabBarItem = tabTwoBarItem
            
            
            self.viewControllers = [tabOne, tabTwo]
        }
    }

**Comment by onmyway133** [comment]
@blurtime Hi,

1. About `Warning: attempt to present ViewController whose view is not in the window hierarchy`,  this is a popular mistake and is not related to `Gallery`, you can easily check it with some SO answers https://stackoverflow.com/questions/15287678/warning-attempt-to-present-viewcontroller-whose-view-is-not-in-the-window-hiera, ...
2. A good advice: you should not setup `view controllers` in `viewWillAppear`, do it in `viewDidLoad` or `init` method

**Comment by blurtime** [comment]
@onmyway133 Hi,

1. Yeah, I encountered that problem once or twice already, so it wouldn't have been a problem. 
2. I am not sure as to why it was in a `viewDidAppear` and what advantages it might have had... can't see any reason why I would have done that. Nonetheless, I'm curious how `viewDidAppear` interferes with adding a sublayer to the view(?). 

I put it in a `viewDidLoad` and now it works! 

Thanks for your patience and help! Really appreciate it!

**Comment by Pulichev** [comment]
@blurtime hello! Can you, please, show screenshot of advancedVideoEditor?
I can't get it work:(
It's not appearing.
Pods updated. 
Only VideoEditor can be showed, but I can't trim in it or etc. Only play video.
Can it be a problem of iOS 9.0?

**Comment by blurtime** [comment]
@Pulichev As far as I'm concerned the video is already trimmed&edited according to the maximum duration as defined under `Config.VideoEditor.maximumDuration`: I believe there is no entire interface for video editing. The video shown ("Only play video.") is the `editedVideo` I think. I am actually using the normal editor and not the advanced one, too.  

If you should create an editor (maybe even with an interface) based on this library though, I would be very happy, if you could share your code since I unfortunately can't write one currently.
