### ISSUE TITLE
Demo has updated code but pods does not have update code. 

### ISSUE THREAD

**Issue by ChanchalW** [hyperoslo/Gallery#42]
## Demo project contains many features like:

public struct Config 
{
    
    @available(*, deprecated, message: "Use tabsToShow instead.")
    public static var showsVideoTab: Bool {
        // Maintains backwards-compatibility.
        get {
            return tabsToShow.index(of: .videoTab) != nil
        }
        set(newValue) {
            if !newValue {
                tabsToShow = tabsToShow.filter({$0 != .videoTab})
            } else {
                if tabsToShow.index(of: .videoTab) == nil {
                    tabsToShow.append(.videoTab)
                }
            }
        }
    }
    public static var tabsToShow: [GalleryTab] = [.imageTab, .cameraTab, .videoTab]
    // Defaults to cameraTab if present, or whatever tab is first if cameraTab isn't present.
    public static var initialTab: GalleryTab?
    
    public enum GalleryTab {
        case imageTab
        case cameraTab
        case videoTab
    }
}

## **But When I install pods (tried Carthage also)**

public struct Config 
{

    public static var showsVideoTab: Bool = true
    public struct PageIndicator {
        public static var backgroundColor: UIColor = UIColor(red: 0, green: 3/255, blue: 10/255, alpha: 1)
        public static var textColor: UIColor = UIColor.white
    }
    
    public struct Camera {
        
        public static var recordLocation: Bool = false
        
        public struct ShutterButton {
            public static var numberColor: UIColor = UIColor(red: 54/255, green: 56/255, blue: 62/255, alpha: 1)
        }
        
        public struct BottomContainer {
            public static var backgroundColor: UIColor = UIColor(red: 23/255, green: 25/255, blue: 28/255, alpha: 0.8)
        }
        
        public struct StackView {
            public static let imageCount: Int = 4
        }
        
        public static var imageLimit: Int = 0
        
    }
}

**## This code just an example for issue reference.** 
Is there is anything wrong? I tried pod update and Carthage update. But I can see the latest version of both but I can't find the code. I know I can add project directly (drag n drop) but I don't want to do that. This will restrict me to get an updated framework in future.

**Comment by onmyway133** [comment]
@ChanchalW Hi, you're right. It is because new pod has not been pushed yet. We will fix this soon

**Comment by ChanchalW** [comment]
Ok can you tell me is it going to take a long time?  or any expected time you can tell me.

**Comment by onmyway133** [comment]
@ChanchalW Hi, you can check https://github.com/hyperoslo/Gallery/releases/tag/1.3.0

**Comment by ChanchalW** [comment]
Hey, thanks @onmyway133  
Appreciate your work and you are the only person who replies so fast and resolved this also.

**Comment by onmyway133** [comment]
@ChanchalW You're welcome 😉

**Comment by ChanchalW** [comment]
Hey @onmyway133  
Just one suggestion for   uiImage(ofSize: SIZE)  method,  you should add a property in Image class called original image (UIImage) with the original image. 
I used image.uiImage(ofSize: PHImageManagerMaximumSize) for it but still, framework should provide us UIImage. Isn't it?
