### ISSUE TITLE
Edit without reducing width and height 

### ISSUE THREAD

**Issue by blurtime** [hyperoslo/Gallery#45]
Hello @onmyway133, 

I have yet another problem: After selecting and having edited a video so its duration is no more than 12 seconds, I would like to upload this video to my server. Uploading it works fine and I use the `tempPath` of the `edit` function to get the editedVideo's URL. However, I noticed something about the videos uploaded to my server as well as saved if `savesEditedVideoToLibrary` was `true`: Namely that its dimensions were modified, e.g. all the videos which had dimensions of 720 x 1280 would end up with a resolution of 202 x 360 on my server. Setting `shouldOptimizeForNetworkUse` in `VideoEditor` to `false` did unfortunately not solve the issue.

How can I solve this problem and only edit its duration (if necessary)?

**Comment by blurtime** [comment]
I really do not want to be annoying but can you please explain how I can edit the video without reducing its quality? Maintaining the video's quality is crucial for my current project... :/ @onmyway133

**Comment by onmyway133** [comment]
@blurtime Hi, sorry for delay response, I was busy recently. 

Firstly, the quality is determined by `preferredPresetName`, you can take a look https://github.com/hyperoslo/Gallery/blob/master/Sources/Utils/VideoEditor/EditInfo.swift#L73
Secondly, `VideoEditor` performs both crops and trim https://github.com/hyperoslo/Gallery/blob/master/Sources/Utils/VideoEditor/EditInfo.swift#L11 so we may create your own VideoEditor and play around with it. 

This https://www.raywenderlich.com/94404/play-record-merge-videos-ios-swift may be a good tutorial for you.

**Comment by blurtime** [comment]
@onmyway133 No problem, I've got the same problem, too... 
I actually like that the video is trimmed (to 12 seconds) and do not desire anything else but trimming (seriously love this library pretty much as it is). The only problem is I do not want it to be cropped, i.e. I would like to maintain its resolution (of e.g. 720 x 1280 pixels) and wasn't able how to do so.
Sorry for so many questions and demands, I'm quite new to video editing...

**Comment by cwestMobile** [comment]
Were you able to resolve this @blurtime blurtime?
