### ISSUE TITLE
Bundle.swift

### ISSUE THREAD

**Issue by 5opr4ni** [hyperoslo/Gallery#50]
Hi, just love the Gallery.

Have a problem tough, Bundle.swift interfere with NSBundle, which now is named Bundle.
(used for getting version number, bulidnumber and such stuff.)

/olle

**Comment by onmyway133** [comment]
@5opr4ni good point. Will note this in the Swift 4 migration

**Comment by onmyway133** [comment]
@5opr4ni Hi, thanks for the suggestion. I renamed it to GalleryBundle https://github.com/hyperoslo/Gallery/pull/55
