### ISSUE TITLE
Delete button in Lightbox does not work

### ISSUE THREAD

**Issue by hstdt** [hyperoslo/Gallery#51]
![gallery](https://user-images.githubusercontent.com/10215098/30676469-ebd315c2-9eb8-11e7-8d99-2a7641960058.gif)
![gallery1](https://user-images.githubusercontent.com/10215098/30676470-ec1f0540-9eb8-11e7-9e6e-1a30fd3da938.gif)

**Comment by onmyway133** [comment]
@hstdt Hi, are you running the example app? Also, this is Lightbox related, please move your question here https://github.com/hyperoslo/Lightbox, thanks

**Comment by hstdt** [comment]
@onmyway133 

Yes, I'm running example project.I'm not sure whether it's a problem related to Gallery or Lightbox, the label below `1/4`-->`1/3`-->`1/2` perform correct.

**Comment by IvanGzx** [comment]
@onmyway133 same issue, may I know how to solve it? thanks
