### ISSUE TITLE
Video Editor is crashing

### ISSUE THREAD

**Issue by ch-muhammad-adil** [hyperoslo/Gallery#57]
My requirements are I have to open Gallery from Tab Bar Controller on pressing camera button. So it open video in full screen after selection hopefully for editing. I could not edit or play more with video. I got this crash. 

2017-10-08 22:19:09.430663+0500 MOD[1368:468010] *** Terminating app due to uncaught exception 'UIViewControllerHierarchyInconsistency', reason: 'child view controller:<AVFullScreenPlaybackControlsViewController: 0x102805200> should have parent view controller:<AVPlayerViewController: 0x1020c7a00> but actual parent is:<AVFullScreenViewController: 0x101be8550>'
*** First throw call stack:
(0x1820bafe0 0x180b1c538 0x1820baf28 0x188267ccc 0x1881f4914 0x1881f3d88 0x1881f3bc8 0x18f959aa8 0x18f9585c0 0x182ae5050 0x182ac0d08 0x182ac0830 0x182aab790 0x18f9530e4 0x18f952df4 0x188203760 0x181fa9e34 0x181fa9d30 0x1881f2440 0x1881e649c 0x1883813e8 0x188380ec0 0x18831de64 0x18827be5c 0x18838196c 0x188222020 0x188366668 0x1882a6704 0x1881f3710 0x188261a80 0x188261a54 0x1882e66dc 0x18855c440 0x18855dcd0 0x1885607e4 0x1882dd794 0x18f95aa00 0x18f95db44 0x18f983a58 0x188221c54 0x188221bd4 0x18820c148 0x1882214b8 0x1887b60e8 0x1887b2434 0x1820689a8 0x182066630 0x182066a7c 0x181f96da4 0x183a01074 0x188251c9c 0x100047df0 0x180fa559c)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by onmyway133** [comment]
@ch-muhammad-adil Hi, it is crashing because `Terminating app due to uncaught exception 'UIViewControllerHierarchyInconsistency`, not really related to video editor. Please check how you set up your view controller hierarchy

**Comment by ch-muhammad-adil** [comment]
@onmyway133  it is UITabBarController, on pressing a tab button i am just presenting Gallery..

**Comment by onmyway133** [comment]
@ch-muhammad-adil Hi, sorry for late response. Can you recreate the issue with a simple project and send to us so that we can inspect further?

**Comment by vijayevolgence** [comment]
"The file “IMG_0489.MOV” couldn’t be opened because you don’t have permission to view it
I'm getting this issue?

**Comment by ch-muhammad-adil** [comment]
Hey i have moved on, i am not following it anymore :) thanks
