### ISSUE TITLE
Error when Bundle was renamed

### ISSUE THREAD

**Issue by dmartinw** [hyperoslo/Gallery#58]
Hi,

When you renamed the class Bundle to GalleryBundle, you made a mistake. You forgot to change Bundle.self to GalleryBundle.self

class GalleryBundle {

  static func image(_ named: String) -> UIImage? {
    let bundle = Foundation.Bundle**(for: GalleryBundle.self)**
    return UIImage(named: "Gallery.bundle/\(named)", in: bundle, compatibleWith: nil)
  }
}

Now the library is crashing.

Bye!

**Comment by onmyway133** [comment]
@dmartinw Hi, sorry for that. You can now check https://github.com/hyperoslo/Gallery/releases/tag/2.0.1
