### ISSUE TITLE
Tab Selection

### ISSUE THREAD

**Issue by jnkfong** [hyperoslo/Gallery#59]
Is it possible to hide or select which tabs to show?

**Comment by zenangst** [comment]
Hey @jnkfong, unfortunately the answer is no. Gallery wasn't built to support making the different sections optional.

For more information you could checkout:
- https://github.com/hyperoslo/Gallery/blob/master/Sources/Gallery/GalleryController.swift
- https://github.com/hyperoslo/Gallery/blob/master/Sources/Utils/Pages/PagesController.swift

I'm afraid supporting this kind of behavior might end up being a lot of work, feel free to fork it and hide the tabs that you don't want to show up.
