### ISSUE TITLE
Value of type 'Image' has no member 'uimage'

### ISSUE THREAD

**Issue by cwestMobile** [hyperoslo/Gallery#63]
let lightboxImages = images.flatMap { $0.uimage(ofSize: UIScreen.main.bounds.size)}.map({ LightboxImage(image: $0 )})

This line has the following error in your demo project: Value of type 'Image' has no member 'uimage'

Please post a fix/idea for fix. Thanks.

**Comment by onmyway133** [comment]
@cwestMobile Hi, you should use the `uiImage` function on `Image`, as that will fetch `UIImage` from `PHImageManager` synchronously

**Comment by cwestMobile** [comment]
Can you provide a code sample of this at all?

**Comment by petekeller2** [comment]
You would now use resolve. There is a sample of this in the example.
