### ISSUE TITLE
iPhone X support

### ISSUE THREAD

**Issue by leobouilloux** [hyperoslo/Gallery#65]
Hello,

Could you please add support for iPhone X?
Some buttons are not reachable (close, flash, ...)
The home bar is also conflicting with the bottom bar.

![img_7e21df0d41cb-1](https://user-images.githubusercontent.com/1726316/33066179-e9061cbe-ceaa-11e7-8458-beadf2e7e678.jpeg)

Thank you very much,

**Comment by onmyway133** [comment]
@leobouilloux Hi, can you check out the latest from `master` to see if it works for you?

**Comment by leobouilloux** [comment]
Hello @onmyway133 ,

Thank you so much, it's perfect now:
![img_41169c5ba0db-1](https://user-images.githubusercontent.com/1726316/33074487-ab36c6ba-cec6-11e7-8645-e85f865b2786.jpeg)

**Comment by onmyway133** [comment]
@leobouilloux Hi, you can now check https://github.com/hyperoslo/Gallery/releases/tag/2.0.3
