### ISSUE TITLE
International support

### ISSUE THREAD

**Issue by liuyu18** [hyperoslo/Gallery#68]
I want to make the display text, such as the button "Done" to change Chinese, thank you

**Comment by onmyway133** [comment]
@liuyu18 Hi, there's some strings that use `NSLocalizedString`, like https://github.com/hyperoslo/Gallery/blob/master/Sources/Utils/View/GridView.swift#L128 so you can have that key in your `Localizable.strings` file

**Comment by liuyu18** [comment]
Thank you, my friend
