### ISSUE TITLE
Gallery not reseting after controller release

### ISSUE THREAD

**Issue by Dfmarulanda** [hyperoslo/Gallery#7]
I think the main idea is that gallery retain objects if you're inside the gallery parent controller, so you can check what's selected at the moment, but, when you release the parent controller, cart keep the references of the objects. deInit function of GalleryController is not triggered.

**Comment by onmyway133** [comment]
@Dfmarulanda you're right, because `Cart` is singleton now to make message callback easy. We can improve this

**Comment by onmyway133** [comment]
@Dfmarulanda Hi, you can checkout https://github.com/hyperoslo/Gallery/releases/tag/1.2.0 which inject Cart instead of using singleton, it may fix your issue
