### ISSUE TITLE
Camera permission is not asked

### ISSUE THREAD

**Issue by zois** [hyperoslo/Gallery#79]
Latest Xcode and latest iOS11 SDK.
When I start with image and camera tab, no permission is asked for camera. Hence, only the image tab is shown.
When I start only with the camera tab, then it asks for camera permission.
Relevant plist keys are there.

What I did is force ask for permission myself in ViewDidLoad

```
AVCaptureDevice.requestAccess(for: AVMediaType.video) { response in
			if response {
				//access granted
			} else {

			}
		}
```

Hint: I have another library that asks for photo library permission when the app starts. Maybe that's related on how internally your library handles the permissions?

**Comment by onmyway133** [comment]
@zois Hi, in iOS, the camera or photo library permission is asked only once, no matter how many times you call `requestAccess`. Maybe that's your case ?

**Comment by zois** [comment]
Yes, I know that they are asked once. What I am saying is that the camera permission is not asked at all. 
If I use this
Gallery.Config.tabsToShow = [.imageTab, .cameraTab]
the camera permission is not asked
But if I use this
Gallery.Config.tabsToShow = [.cameraTab]
it's indeed asked.
Now as i said, I have another library that uses the photo permission before Gallery, so I am asked for the photo permission. Hence, I don't expect Gallery to ask me again for the photo permission but I am expecting it to ask for the camera. This is not happening and that's the issue.
So I am asking for camera permission myself to solve this.

regards

**Comment by paulius005** [comment]
Im experiencing the same issue with Mojave, @zois did you ever figure this out?
