### ISSUE TITLE
The image preview 

### ISSUE THREAD

**Issue by jackpaster** [hyperoslo/Gallery#8]
@zenangst @fespinoza @nashby @timkurvers @sindrenm First of all this project is amazing, but I have a problem. once ive taken the images i want to preview them in this custom view controller i made with a scroll view inside of it. The lightbox solution you have for presenting your images and videos is nice but do you have something custom like a lightbox scroll view instead of a lightbox view controller that I can call in my main.storyboard so I can have additional elements in my view controller alongside the lightbox scroll view. 

Skype: Jackpaster22

**Comment by onmyway133** [comment]
@jackpaster Hi, you make the same issue twice, I think we will close this and discuss on https://github.com/hyperoslo/Gallery/issues/9 instead
