### ISSUE TITLE
PageController latest changes not available in latest pod 2.0.5

### ISSUE THREAD

**Issue by zois** [hyperoslo/Gallery#80]
Remember your last fix in PageController regarding the constraint crashes?
Well this fix is not there when we get Gallery via pod (latest 2.0.5). It has the old code.
What I did is took the code from master, unlocked the pod in Xcode and replaced PageController.swift with the latest one.

**Comment by onmyway133** [comment]
@zois Hi, sorry for the delay. You can now use https://github.com/hyperoslo/Gallery/releases/tag/2.0.6

**Comment by zois** [comment]
Ok, thanks.
