### ISSUE TITLE
Variable set of modes

### ISSUE THREAD

**Issue by richardtop** [hyperoslo/Gallery#85]
It would be good to add an option to configure which tabs should be open. E.g. for some cases, there is no need for video or gallery.

**Comment by onmyway133** [comment]
@richardtop Hi, I think we have 
`tabsToShow` https://github.com/hyperoslo/Gallery/blob/master/Sources/Utils/Config.swift#L22, is it what you need?

**Comment by richardtop** [comment]
@onmyway133 thanks, that's exactly the feature I was looking for.

I'd add description to readme, I think it's the feature that needed quite often.
