### ISSUE TITLE
Need do add protocols after you add them

### ISSUE THREAD

**Issue by mohyM** [hyperoslo/Gallery#90]
When you add protocols you have error to add protocols again and again

**Comment by Bogdan148** [comment]
I have the same problem, because in my project the classes have the same name with the names of the source pod classes

**Comment by AdnanYupi** [comment]
Does anyone know what is causing this problem? I tried today and got the same issue even if I added protocols and need to add them again?

**Comment by moooooooooody** [comment]
I solved this problem by renaming my classes
